# Generated by Django 6.1.1 on 2026-09-21 14:44

import django.db.models.deletion
import uuid
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('text', 1), ('image', 4), ('video', 5), ('document', 8), ('button', 12), ('simulation', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste a public video URL, for example YouTube or Vimeo.'}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional public label. The document title is used if this is empty.', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('document', 6), ('label', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 10: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 11: ('wagtail.blocks.URLBlock', (), {'help_text': 'Use this for an external link.', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 9), ('page', 10), ('url', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 14: ('wagtail.blocks.TextBlock', (), {'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL of a prepared, trusted interactive simulation. Do not paste JavaScript here.'}), 16: ('wagtail.blocks.StructBlock', [[('title', 13), ('description', 14), ('embed_url', 15)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('text', 1), ('image', 4), ('video', 5), ('document', 8), ('button', 12), ('simulation', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste a public video URL, for example YouTube or Vimeo.'}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional public label. The document title is used if this is empty.', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('document', 6), ('label', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 10: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 11: ('wagtail.blocks.URLBlock', (), {'help_text': 'Use this for an external link.', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 9), ('page', 10), ('url', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 14: ('wagtail.blocks.TextBlock', (), {'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL of a prepared, trusted interactive simulation. Do not paste JavaScript here.'}), 16: ('wagtail.blocks.StructBlock', [[('title', 13), ('description', 14), ('embed_url', 15)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PeopleIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('text', 1), ('image', 4), ('video', 5), ('document', 8), ('button', 12), ('simulation', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste a public video URL, for example YouTube or Vimeo.'}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional public label. The document title is used if this is empty.', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('document', 6), ('label', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 10: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 11: ('wagtail.blocks.URLBlock', (), {'help_text': 'Use this for an external link.', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 9), ('page', 10), ('url', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 14: ('wagtail.blocks.TextBlock', (), {'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL of a prepared, trusted interactive simulation. Do not paste JavaScript here.'}), 16: ('wagtail.blocks.StructBlock', [[('title', 13), ('description', 14), ('embed_url', 15)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('text', 1), ('image', 4), ('video', 5), ('document', 8), ('button', 12), ('simulation', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste a public video URL, for example YouTube or Vimeo.'}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional public label. The document title is used if this is empty.', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('document', 6), ('label', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 10: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 11: ('wagtail.blocks.URLBlock', (), {'help_text': 'Use this for an external link.', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 9), ('page', 10), ('url', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 14: ('wagtail.blocks.TextBlock', (), {'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL of a prepared, trusted interactive simulation. Do not paste JavaScript here.'}), 16: ('wagtail.blocks.StructBlock', [[('title', 13), ('description', 14), ('embed_url', 15)]], {})})),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('funder', models.CharField(blank=True, max_length=255)),
                ('external_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('text', 1), ('image', 4), ('video', 5), ('document', 8), ('button', 12), ('simulation', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste a public video URL, for example YouTube or Vimeo.'}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional public label. The document title is used if this is empty.', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('document', 6), ('label', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 10: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 11: ('wagtail.blocks.URLBlock', (), {'help_text': 'Use this for an external link.', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 9), ('page', 10), ('url', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 14: ('wagtail.blocks.TextBlock', (), {'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL of a prepared, trusted interactive simulation. Do not paste JavaScript here.'}), 16: ('wagtail.blocks.StructBlock', [[('title', 13), ('description', 14), ('embed_url', 15)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SciencePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('text', 1), ('image', 4), ('video', 5), ('document', 8), ('button', 12), ('simulation', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste a public video URL, for example YouTube or Vimeo.'}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional public label. The document title is used if this is empty.', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('document', 6), ('label', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 10: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 11: ('wagtail.blocks.URLBlock', (), {'help_text': 'Use this for an external link.', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 9), ('page', 10), ('url', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 14: ('wagtail.blocks.TextBlock', (), {'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL of a prepared, trusted interactive simulation. Do not paste JavaScript here.'}), 16: ('wagtail.blocks.StructBlock', [[('title', 13), ('description', 14), ('embed_url', 15)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('text', 1), ('image', 4), ('video', 5), ('document', 8), ('button', 12), ('simulation', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste a public video URL, for example YouTube or Vimeo.'}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional public label. The document title is used if this is empty.', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('document', 6), ('label', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 10: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 11: ('wagtail.blocks.URLBlock', (), {'help_text': 'Use this for an external link.', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 9), ('page', 10), ('url', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 14: ('wagtail.blocks.TextBlock', (), {'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL of a prepared, trusted interactive simulation. Do not paste JavaScript here.'}), 16: ('wagtail.blocks.StructBlock', [[('title', 13), ('description', 14), ('embed_url', 15)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='About BIG Lab', max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('text', 1), ('image', 4), ('video', 5), ('document', 8), ('button', 12), ('simulation', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste a public video URL, for example YouTube or Vimeo.'}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional public label. The document title is used if this is empty.', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('document', 6), ('label', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 10: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 11: ('wagtail.blocks.URLBlock', (), {'help_text': 'Use this for an external link.', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 9), ('page', 10), ('url', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 14: ('wagtail.blocks.TextBlock', (), {'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL of a prepared, trusted interactive simulation. Do not paste JavaScript here.'}), 16: ('wagtail.blocks.StructBlock', [[('title', 13), ('description', 14), ('embed_url', 15)]], {})})),
                ('date', models.DateField(verbose_name='publication date')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PersonPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('text', 1), ('image', 4), ('video', 5), ('document', 8), ('button', 12), ('simulation', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste a public video URL, for example YouTube or Vimeo.'}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional public label. The document title is used if this is empty.', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('document', 6), ('label', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 10: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 11: ('wagtail.blocks.URLBlock', (), {'help_text': 'Use this for an external link.', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 9), ('page', 10), ('url', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 14: ('wagtail.blocks.TextBlock', (), {'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL of a prepared, trusted interactive simulation. Do not paste JavaScript here.'}), 16: ('wagtail.blocks.StructBlock', [[('title', 13), ('description', 14), ('embed_url', 15)]], {})})),
                ('role', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_url', models.URLField(blank=True, help_text='Optional external profile URL.')),
                ('portrait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'collaboration',
                'verbose_name_plural': 'collaborations',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.TextField(help_text='List authors in the desired display order.')),
                ('year', models.PositiveSmallIntegerField()),
                ('publication_type', models.CharField(blank=True, max_length=120)),
                ('journal_or_publisher', models.CharField(blank=True, max_length=255)),
                ('doi_or_url', models.URLField(blank=True)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
                'ordering': ['-year', 'title'],
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
    ]
