# Generated by Django 6.1.1 on 2026-10-03 19:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_repair_empty_sections'),
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacetext',
            name='key',
            field=models.CharField(choices=[('research_disciplines', 'Psychology · Sociology · Network science'), ('discover_lab', 'Discover BIG Lab'), ('network_hint', 'Move or tap the network'), ('switch_design', 'Switch homepage design'), ('about', 'About'), ('science', 'Science'), ('people', 'People'), ('news', 'News'), ('projects', 'Projects'), ('current_projects', 'Current projects'), ('finished_projects', 'Finished projects'), ('publications', 'Publications'), ('collaborations', 'Collaborations'), ('contact', 'Contact'), ('menu', 'Menu'), ('close', 'Close'), ('skip_content', 'Skip to content'), ('main_navigation', 'Main navigation'), ('language', 'Language'), ('home', 'Home'), ('explore_science', 'Explore our science'), ('meet_team', 'Meet the team'), ('all_science', 'All science'), ('full_team', 'Full team'), ('about_project', 'About the project'), ('back', 'Back'), ('project', 'Project'), ('project_website', 'Project website'), ('start', 'Start'), ('end', 'End'), ('funder', 'Funder'), ('explore', 'Explore'), ('read_more', 'Read more'), ('previous_people', 'Previous people'), ('next_people', 'Next people'), ('team_members', 'Team members'), ('previous_image', 'Previous image'), ('next_image', 'Next image'), ('image_preview', 'Image preview'), ('open_image', 'Open image'), ('download', 'Download'), ('simulation', 'Simulation'), ('results', 'Results'), ('timeline', 'Timeline'), ('for_parents', 'For parents'), ('for_schools', 'For schools'), ('for_students', 'For students'), ('contents', 'Contents'), ('profile', 'Profile'), ('empty_news', 'No news has been published yet.'), ('empty_publications', 'No publications have been added yet.'), ('empty_projects', 'No projects have been published yet.'), ('empty_people', 'No team profiles have been published yet.'), ('contact_intro', 'Get in touch with BIG Lab.'), ('footer_tagline', 'Behaviour, interactions and groups'), ('institute_social', 'INPSY institute social media'), ('research_areas', 'Research areas'), ('in_progress', 'In progress'), ('before', 'Before'), ('after', 'After'), ('email', 'Email'), ('phone', 'Phone'), ('address', 'Address'), ('financing', 'Financing'), ('contact_us', 'Contact us'), ('view_all', 'View all'), ('show_more', 'Show more'), ('show_less', 'Show less'), ('play', 'Play'), ('pause', 'Pause')], help_text='Choose the built-in label to override in this language. Select the same label for each translation.', max_length=100, verbose_name='Interface label to translate'),
        ),
        migrations.CreateModel(
            name='HomepageDesignSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(default='#0b141e', help_text='Background of the homepage in Version 2 only. Use #RRGGBB.', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_hex_color', message='Enter a six-digit hexadecimal color, for example #0b141e.', regex='\\A#[0-9a-fA-F]{6}\\Z')], verbose_name='Version 2 background')),
                ('foreground', models.CharField(default='#eeeae0', help_text='Main text on the homepage in Version 2 only. Use #RRGGBB.', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_hex_color', message='Enter a six-digit hexadecimal color, for example #0b141e.', regex='\\A#[0-9a-fA-F]{6}\\Z')], verbose_name='Version 2 foreground')),
                ('accent', models.CharField(default='#dac99c', help_text='Actions and primary network connections on the homepage in Version 2 only. Use #RRGGBB.', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_hex_color', message='Enter a six-digit hexadecimal color, for example #0b141e.', regex='\\A#[0-9a-fA-F]{6}\\Z')], verbose_name='Version 2 accent')),
                ('muted', models.CharField(default='#a6b4bd', help_text='Supporting text on the homepage in Version 2 only. Use #RRGGBB.', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_hex_color', message='Enter a six-digit hexadecimal color, for example #0b141e.', regex='\\A#[0-9a-fA-F]{6}\\Z')], verbose_name='Version 2 muted text')),
                ('network_secondary', models.CharField(default='#7f9d98', help_text='Secondary network strands on the homepage in Version 2 only. Use #RRGGBB.', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_hex_color', message='Enter a six-digit hexadecimal color, for example #0b141e.', regex='\\A#[0-9a-fA-F]{6}\\Z')], verbose_name='Version 2 secondary network color')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'homepage design (Version 2)',
            },
        ),
    ]
