# Generated by Django 6.1.1 on 2026-10-04 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_homepage_design_settings'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsettings',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Shared logo for the website header, footer, browser icon and CMS. Change it here once to update every location. Leave blank to use the default BIG Lab logo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
